### get all account
GET http://localhost:3003/accounts

### get account por id

GET http://localhost:3003/accounts/a002

####put account por id

PUT http://localhost:3003/accounts/a002
content-type: application/json

{
    "id": "id-teste",
    "ownerName": "teste",
    "balance": 50000,
    "type": "Ouro"
}

###delete account por id

DELETE http://localhost:3003/accounts/a001
